theme: "just-the-docs"

exclude:
  - "*.pxm"
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

title: OOPP
description: >- # this means to ignore newlines until "baseurl:"
  Website and assignments for the OOP Project (CSE1105) at Delft University of Technology.
  This course is part of the bachelor of Computer Science and Engineering.
baseurl: "/oopp"
url: "https://se.ewi.tudelft.nl"
permalink: /:categories/:title/

surfdrive_id: "VK2lHxm0GgUmqLF" # the hash from a surfdrive link
surfdrive: "https://surfdrive.surf.nl/files/index.php/s/VK2lHxm0GgUmqLF"

# OOPP Specific things ----------------------------------------------------------------------------------------
color_scheme: tudelft
logo: "assets/images/tudelft.png"
# Links that show in the top right
aux_links:
  "GitLab":
    - "https://gitlab.ewi.tudelft.nl/cse1105/2022-2023/"
  "Brightspace":
    - "https://brightspace.tudelft.nl/d2l/home/499389"
  "Studyguide":
    - "https://studyguide.tudelft.nl/a101_displayCourse.do?course_id=61477"
  "Q&A":
    - "https://answers.ewi.tudelft.nl/categories/1/tags/123"
aux_links_new_tab: false
